
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip2.txt ModelsCNN/ 2
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip3.txt ModelsCNN/ 3
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip4.txt ModelsCNN/ 4
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip5.txt ModelsCNN/ 5
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip7.txt ModelsCNN/ 7
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip10.txt ModelsCNN/ 10
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip11.txt ModelsCNN/ 11
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip12.txt ModelsCNN/ 12
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip13.txt ModelsCNN/ 13
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip14.txt ModelsCNN/ 14
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip15.txt ModelsCNN/ 15
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip16.txt ModelsCNN/ 16
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip17.txt ModelsCNN/ 17
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip18.txt ModelsCNN/ 18
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip19.txt ModelsCNN/ 19
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip20.txt ModelsCNN/ 20
#
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip23.txt ModelsCNN/ 23
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip25.txt ModelsCNN/ 25
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip27.txt ModelsCNN/ 27
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip30.txt ModelsCNN/ 30
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip33.txt ModelsCNN/ 33
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip35.txt ModelsCNN/ 35
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip37.txt ModelsCNN/ 37
#./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip40.txt ModelsCNN/ 40

./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip6.txt ModelsCNN/ 6
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip8.txt ModelsCNN/ 8
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip9.txt ModelsCNN/ 9
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip21.txt ModelsCNN/ 21
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip22.txt ModelsCNN/ 22
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip23.txt ModelsCNN/ 23
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip24.txt ModelsCNN/ 24
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip26.txt ModelsCNN/ 26
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip28.txt ModelsCNN/ 28
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip29.txt ModelsCNN/ 29
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip31.txt ModelsCNN/ 31
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip32.txt ModelsCNN/ 32
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip34.txt ModelsCNN/ 34
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip36.txt ModelsCNN/ 36
./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM3.yaml ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz ~/Data/TUM/rgbd_dataset_freiburg3_walking_xyz/associations.txt results/w_xyz_Dyna_skip38.txt ModelsCNN/ 38


